final Map<String, List<dynamic>> lessonsCeloso = {
  "lesson1": [
    {
      "type": "image",
      "path": "lib/assets/images/lesson1-1.png",
    },
    "The students will study polygons, the types, definitions and properties of a polygon. Besides identifying key properties such as the number of sides, angles, and symmetry, they will also differentiate between a regular and an irregular polygon and a convex and a concave polygon. Students will strengthen their understanding of geometric concepts by constructing polygons using rulers, protractors, and graph paper. They will apply mathematical operations which they learn to find inner and outer angles, to create polygons correctly of specific measurements.",
    {
      "type": "image",
      "path": "lib/assets/images/triangle.png",
    },
    "1. Equilateral Triangle (3 sides)",
    "-Use a ruler to draw a base of 6 cm.",
    "-Use a protractor to measure two 60° angles at each endpoint.",
    "-Draw the other two sides to complete the triangle.",
    {
      "type": "image",
      "path": "lib/assets/images/square.png",
    },
    "2. Square (4 sides, all equal)",
    "-Draw a horizontal line of 5 cm.",
    "-Use a protractor to mark 90° angles at both ends.",
    "-Draw two vertical lines 5 cm each, then connect the top ends.",
    {
      "type": "image",
      "path": "lib/assets/images/pentagon.png",
    },
    "3. Regular Pentagon (5 sides, equal length)",
    "-Draw a 5 cm base using a ruler.",
    "-Use a protractor to measure 108° angles at both endpoints.",
    "-Continue drawing sides of 5 cm each until you complete the pentagon.",
    {
      "type": "image",
      "path": "lib/assets/images/irregular.png",
    },
    "4. Irregular Quadrilateral (4 sides, different lengths)",
    "-Draw a 6 cm base and a 4 cm vertical side at any angle.",
    "-Connect two more sides with different lengths and angles to form a closed shape.",
    {
      "type": "image",
      "path": "lib/assets/images/hexagon.png",
    },
    "5. Hexagon (6 sides, regular)",
    "-Draw a 5 cm base.",
    "-Use a protractor to measure 120° angles at each endpoint.",
    "-Continue adding 5 cm sides at correct angles until all six sides are complete.",
  ],
  "lesson2": [
    "Polygons and Convexity besides identifying key properties such as the number of sides, angles, and symmetry, they will also differentiate between a regular and an irregular polygon and a convex and a concave polygon. Students will strengthen their understanding of geometric concepts by constructing polygons using rulers, protractors, and graph paper. They will apply mathematical operations which they learn to find inner and outer angles, to create polygons correctly of specific measurements.",
    "Example:",
    {
      "type": "image",
      "path": "lib/assets/images/lesson2-1.png",
    },
    "Convex Polygons (All interior angles < 180°)",
    "Equilateral Triangle – A triangle with all sides and angles equal (60° each).",
    "Square – A four-sided shape with all angles at 90° and equal sides.",
    "Regular Pentagon – A five-sided polygon where all sides and angles are equal.",
    "Hexagon (Regular or Irregular, if no angles > 180°) – A six-sided figure with equal angles in a regular hexagon.",
    "2. Concave Polygons (At least one interior angle > 180°)",
    "Arrowhead Quadrilateral – A four-sided shape where one interior angle is greater than 180°.",
    "Star-shaped Polygon – A shape with indented sides that create reflex angles (>180°).",
    "Irregular Concave Pentagon – A five-sided figure with one or more angles greater than 180°.",
    "3. Real-World Examples",
    "Convex Shapes:",
    "-A stop sign (octagon)",
    "-A honeycomb cell (hexagon)",
    "-A window pane (square or rectangle)",
    "-Concave Shapes:",
    "-A boomerang (concave quadrilateral)",
    "-A star-shaped badge",
    "-The outline of a crescent moon",
  ],
  "lesson3": [
    "This lesson will introduce students to the fundamental concepts of polygons, including their definitions, properties, and classifications. They will learn to recognize key characteristics such as the number of sides, angles, and symmetry. Additionally, students will distinguish between regular and irregular polygons as well as convex and concave polygons. Worksheets allow students to practice and deve lop their understanding of geometry in smaller tasks by constructing polygons with rulers, protractors, and graph paper. They will also use math equations to calculate angle measures and the sum of interior and exterior angles in order to accurately draw polygons given certain measurements.",
    "1. Identifying Polygons by Sides",
    "Triangle (3 sides) – Example: A road sign with a triangular shape.",
    "Quadrilateral (4 sides) – Example: A rectangular picture frame.",
    "Pentagon (5 sides) – Example: The Pentagon building in the U.S.",
    "Hexagon (6 sides) – Example: A honeycomb cell.",
    "2. Regular vs. Irregular Polygons",
    "Regular Polygon: All sides and angles are equal.",
    "Example: A stop sign (octagon with equal sides).",
    "Irregular Polygon: Sides and angles are not equal.",
    "Example: A plot of land with uneven boundaries.",
    "3. Convex vs. Concave Polygons",
    "Convex Polygon: All interior angles are less than 180°.",
    "Example: A soccer field (rectangular shape).",
    "Concave Polygon: At least one interior angle is greater than 180°.",
    "Example: A star-shaped badge.",
  ],
  "lesson4": [
    "This lesson introduces students to the fundamental concepts of percentages and rates, helping them understand how these mathematical tools are used in everyday life. Students will learn how to calculate percentages of a number, percentage increases and decreases, and the relationship between percentages, fractions, and decimals.",
    "Additionally, they will explore the concept of rates, which compare two different quantities with different units (e.g., speed in kilometers per hour or price per kilogram). Through real-world examples and problem-solving exercises, students will develop the skills needed to apply percentages and rates in financial literacy, discounts, interest calculations, and data interpretation.",
    {
      "type": "image",
      "path": "lib/assets/images/img1.png",
    },
    "1. Percentages:",
    "Percentages are a way of expressing a number as a fraction of 100.",
    "Example 1 (Discounts): A shirt costs \$50, and there is a 20% discount. The discount amount is:"
        "50×20100=1050 \\times \\frac{20}{100} = 1050×10020​=10",
    "So, the final price = \$50 - \$10 = \$40.",
    "Example 2 (Exam Score): You answered 80 questions correctly out of 100. Your percentage score is:",
    "80100×100=80%\\frac{80}{100} \\times 100 = 80\\%10080​×100=80%",
    "2. Rates:",
    "A rate is a comparison between two different units.",
    "Example 1 (Speed): A car travels 300 miles in 5 hours. The rate (speed) is:",
    "300 miles5 hours=60 miles per hour(mph)\\frac{300 \\text{ miles}}{5 \\text{ hours}} = 60 \\text{ miles per hour} (mph)5 hours300 miles​=60 miles per hour(mph)",
    "Example 2 (Interest Rate): A bank offers a 5% annual interest rate on savings of \$1,000. The interest earned in one year is:",
    "1000×5100=501000 \\times \\frac{5}{100} = 501000×1005​=50",
    "So, the total amount after a year = \$1,050.",
  ],
  "lesson5": [
    "Rational numbers, their properties, and their applications in real-life situations. Students will learn that rational numbers are numbers that can be expressed as a fraction (ratio of two integers), where the denominator is not zero. The lesson will cover identifying, comparing, and performing operations (addition, subtraction, multiplication, and division) with rational numbers. Additionally, students will explore the difference between terminating and repeating decimals and how they relate to rational numbers. By the end of this lesson, students will be able to recognize rational numbers in various forms and apply their knowledge in problem-solving situations.",
    "Fraction Form:",
    "34\\frac{3}{4}43​ (Three-fourths)",
    "−72\\frac{-7}{2}2−7​ (Negative seven-halves)",
    "Whole Numbers (which can be written as fractions):",
    "555 (can be written as 51\\frac{5}{1}15​)",
    "−12-12−12 (can be written as −121\\frac{-12}{1}1−12​)",
    "Decimals (Terminating or Repeating):",
    "Terminating: 0.750.750.75 (which is 34\\frac{3}{4}43​)",
    "Repeating: 0.3‾0.\\overline{3}0.3 (which is 13\\frac{1}{3}31​)",
    "Operations with Rational Numbers:",
    "25+15=35\\frac{2}{5} + \\frac{1}{5} = \\frac{3}{5}52​+51​=53​",
    "0.6×0.5=0.30.6 \\times 0.5 = 0.30.6×0.5=0.3",
  ],
  "lesson6": [
    "Addition and Subtraction of Rational Numbers focuses on the rules and strategies for adding and subtracting rational numbers, including fractions, decimals, and integers. Students will learn how",
    "to find a common denominator when working with fractions and how to correctly apply the sign rules when dealing with negative numbers. They will also explore real-life applications of adding and subtracting rational numbers, such as calculating money, temperature changes, and measurements.",
    "EXAMPLES:",
    "1. Adding and Subtracting Fractions",
    "Same denominator: Add or subtract the numerators and keep the denominator the same.",
    "Different denominators: Find the Least Common Denominator (LCD), adjust the fractions, and then add or subtract.",
    "2. Adding and Subtracting Decimals",
    "Line up the decimal points and perform the operation.",
    "Example:",
    "3.25+1.75=5.003.25 + 1.75 = 5.003.25+1.75=5.00",
    "6.4−2.75=3.656.4 - 2.75 = 3.656.4−2.75=3.65",
    "3. Adding and Subtracting Integers",
    "Same signs: Add the absolute values and keep the common sign.",
    "Example: −4+(−6)=−10-4 + (-6) = -10−4+(−6)=−10",
    "Example: 7+3=107 + 3 = 107+3=10",
    "Different signs: Subtract the smaller absolute value from the larger one and take the sign of the larger number.",
    "Example: −9+4=−5-9 + 4 = -5−9+4=−5",
    "Example: 10−15=−510 - 15 = -510−15=−5",
  ],
  "lesson7": [
    "In this lesson, students learn how to multiply and divide rational numbers, such as integers, fractions, and decimals. Pupils will learn how to simplify fractions, multiply and divide positive and negative numbers, and, if needed, convert between improper fractions and mixed numbers. Additionally, they will investigate practical uses like figuring out rates, proportions, and scaling in various settings. Students will be able to use their knowledge to solve mathematical and real-world problems by the end of the lesson and execute operations on rational numbers with assurance.",
  ],
  "lesson8": [
    "This lesson introduces students to the concept of real numbers, their properties, and how they are classified. Students will explore the different subsets of real numbers, including natural numbers, whole numbers, integers, rational numbers, and irrational numbers. They will also learn how to compare, order, and perform operations with real numbers.",
    "Key Concepts:",
    "Definition of real numbers",
    "Subsets of real numbers (Natural, Whole, Integers, Rational, and Irrational)",
    "Properties of real numbers (Commutative, Associative, Distributive, Identity, Inverse)",
    "Operations with real numbers (Addition, Subtraction, Multiplication, and Division)",
    "Representing real numbers on a number line",
  ],
  "lesson9": [
    "This lesson introduces students to the concept of unit conversions, helping them understand how to convert between different units of measurement. Students will learn about different measurement",
    "systems, including the metric system (meters, liters, grams) and the customary system (inches, feet, pounds). They will explore conversion factors, dimensional analysis, and real-world applications of unit conversion in everyday life, such as cooking, travel, and science.",
    "Key Concepts:",
    "Understanding units of measurement (length, weight/mass, volume, time)",
    "Metric system vs. Customary system",
    "Conversion factors and how to use them",
    "Step-by-step method for converting units",
    "Applications of unit conversions in daily life",
  ],
  "lesson10": [
    "This lesson focuses on understanding the volume of a cylinder, including the formula, step-by-step calculations, and real-world applications. Students will learn how to determine the amount of space a cylinder occupies by using its radius and height. Through guided examples and practice problems, students will develop confidence in solving volume-related problems and applying the concept to real-life situations, such as finding the capacity of a water tank or a can.",
    "Key Concepts:",
    "Definition of a cylinder",
    "Understanding volume as the amount of space occupied by a 3D object",
    "The formula for the volume of a cylinder",
  ],
  "lesson11": [
    "This lesson introduces students to the concept of a rectangular pyramid and teaches them how to calculate its volume. Students will learn the formula for the volume of a pyramid, understand the relationship between a pyramid and a prism, and apply their knowledge to solve real-world problems. Through step-by-step examples, students will gain confidence in computing volumes and recognizing practical applications of rectangular pyramids in architecture, packaging, and construction.",
    "Key Concepts:",
    "Definition of a Rectangular Pyramid: A 3D shape with a rectangular base and triangular faces meeting at a single vertex.",
  ],
  "lesson12": [
    "Students learn about the idea of a rectangular pyramid and how to determine its volume in this lesson. Students will discover how to calculate a pyramid's volume, comprehend how a pyramid and a prism work together, and use what they've learned to solve practical issues. Students will become more comfortable calculating volumes and identifying real-world uses for rectangular pyramids in construction, architecture, and packaging by following detailed examples.",
    "Definition of a Rectangular Pyramid: A 3D shape with a rectangular base and triangular faces meeting at a single vertex.",
    "Volume Formula:",
    "V = 1/3 X B X h",
    "where:",
    "V = Volume",
    "B = Area of the rectangular base (B= length×widthB = \\text{length} \\times \\text{width} B=length×width)",
    "h = Height of the pyramid (perpendicular distance from the base to the vertex)",
  ],
  "lesson13": [
    "The basic ideas behind sets and how they work. Using roster notation and set-builder notation, students will learn how to define and represent sets. Different kinds of sets, such as finite, infinite, universal, null (empty), equal, and equivalent sets, will also be covered in the lesson. Students will also study set operations like complement, difference, intersection, and union. Venn diagrams will be used to illustrate these ideas.",
    "EXAMPLES:",
    "Roster Notation and Set-Builder Notation:",
    "Write the set of vowels in the English alphabet using roster notation.",
    "Express the set of even numbers less than 20 using set-builder notation.",
    "Identifying Types of Sets:",
    "Determine whether the following sets are finite or infinite:",
    "a) A = {2, 4, 6, 8, 10}",
    "b) B = {x | x is a multiple of 5}",
    "Identify whether the set C = { } is an empty set or not.",
    "Set Operations:",
    "Given the sets:",
    "A = {1, 2, 3, 4, 5}",
    "B = {3, 4, 5, 6, 7}",
    "U = {1, 2, 3, 4, 5, 6, 7, 8, 9, 10} (Universal Set)",
    "Solve the following:",
    "Find A ∪ B (Union of A and B).",
    "Find A ∩ B (Intersection of A and B).",
    "Find A - B (Difference of A and B).",
    "Find A' (Complement of A).",
    "Venn Diagram Interpretation:",
    "If Set X represents students who play basketball and Set Y represents students who play soccer, interpret the following:",
    "a) X ∩ Y represents what group of students?",
    "b) X ∪ Y represents what group of students?",
  ],
  "lesson14": [
    "By the end of this lesson, students will understand how to collect and organize data using different methods.",
    "Introduction to Data Collection:",
    "What is Data?",
    "Data refers to raw facts and figures that are collected for analysis. Data can be numerical or categorical, and it helps to provide insights into a particular subject or situation.",
    "Types of Data:",
    "Qualitative Data (Categorical): Data that represents categories or descriptions (e.g., color, type of fruit).",
    "Quantitative Data (Numerical): Data that represents numbers (e.g., age, height, weight).",
    "Methods of Collecting Data:",
    "Surveys or Questionnaires: Asking questions to gather responses.",
    "Observations: Recording what is observed in a particular situation.",
    "Experiments: Conducting tests and recording results.",
    "Interviews: Asking individuals for their thoughts or opinions.",
    "Introduction to Sampling Techniques:",
    "Sometimes it is impractical or impossible to collect data from every individual or element within a population. In these cases, sampling is used to select a smaller group (sample) to represent the larger group (population).",
    "Sampling techniques can be classified into two major types:",
    "Probability Sampling: Involves random selection, giving every member of the population an equal chance of being chosen.",
    "Nonprobability Sampling: Does not involve random selection and may introduce bias, but can be more practical for exploratory research.",
    "Types of Probability Sampling:",
    "a. Simple Random Sampling: Every member of the population has an equal chance of being selected. Often done using random number generators or drawing lots.",
    "b. Stratified Sampling: The population is divided into subgroups (strata) based on specific characteristics (e.g., age, gender), and a random sample is taken from each subgroup.",
    "c. Systematic Sampling: The population is ordered (e.g., alphabetically), and researchers select every nth element from the list (e.g., every 5th student).",
    "d. Cluster Sampling: The population is divided into clusters, and then a random sample of clusters is selected. Every member or a random sample within the chosen clusters is included.",
    "Nonprobability Sampling:",
    "May involve forms of judgment or convenience rather than random selection. This type is less rigorous but can still be useful in exploratory or qualitative research.",
    "Example:",
    "Let's collect the ages of 10 students in a class:",
    "Ages of students: 16, 17, 16, 18, 17, 19, 16, 20, 18, 17.",
    "Step 1: Organize the data in a table.",
    {
      "type": "image",
      "path": "lib/assets/images/img2.png",
    },
    "Step 2: Create a frequency distribution.",
    {
      "type": "image",
      "path": "lib/assets/images/img3.png",
    },
  ],
  "lesson15": [
    "By the end of this lesson, students will understand how to represent and interpret data using tally charts, bar graphs, line graphs, and pie charts.",
    "Introduction to Graphing Data",
    "Definition:",
    "Graphing data allows us to visually represent numerical information, making it easier to identify trends, patterns, or comparisons. Different types of graphs are suited for different types of data. Common types include tally charts, bar graphs, line graphs, and pie charts.",
    "Types of Graphs",
    "Tally Charts",
    "Definition:",
    "A tally chart is a simple method for recording and counting occurrences. It uses tally marks to track how many times a specific event or value occurs. Each set of five tally marks is grouped together for easy counting.",
    "Example:",
    "Suppose a teacher surveys 30 students on their favorite school subject. The data is recorded in a tally chart:",
    {
      "type": "image",
      "path": "lib/assets/images/img4.png",
    },
    "Explanation:",
    "Each tally mark represents one student’s vote. Every fifth tally mark is drawn diagonally to make counting easier. The total column shows the final count for each subject. In this case, 13 students chose Math, 12 chose Science, and 5 chose History.",
    "Bar Graphs",
    "Definition:",
    "A bar graph is used to compare different categories of data. The length or height of the bar represents the value or frequency for each category.",
    "Example:",
    "Using the tally chart data from above, we can create a bar graph to show the number of students who prefer each subject.",
    {
      "type": "image",
      "path": "lib/assets/images/img5.png",
    },
    "Explanation:",
    "Bar graphs are useful for comparing categories visually. In this case, it is easy to see that Math is the most popular subject, followed closely by Science, while History has the fewest students’ votes.",
    "Line Graphs",
    "Definition:",
    "A line graph is used to display data points that are connected by lines, showing changes or trends over time.",
    "Example:",
    "Suppose you are tracking the number of people visiting a museum over the course of five days:",
    {
      "type": "image",
      "path": "lib/assets/images/img6.png",
    },
    "A line graph would show the days on the x-axis and the number of visitors on the y-axis. Each day’s visitor count is represented as a point, and the points are connected by a line to show the trend over time.",
    {
      "type": "image",
      "path": "lib/assets/images/img7.png",
    },
    "Explanation:",
    "Line graphs help visualize changes in data over time. In this case, the graph shows an upward trend in visitors from Monday to Wednesday, followed by a dip on Thursday and a peak on Friday.",
    "Pie Charts",
    "Definition:",
    "A pie chart is a circular graph divided into slices, where each slice represents a proportion of the whole.",
    "Example:",
    "Let’s say a survey is conducted to find out students’ favorite types of food, with the following results:",
    {
      "type": "image",
      "path": "lib/assets/images/img8.png",
    },
    "A pie chart would represent these percentages as slices of the circle, with Pizza taking up the largest portion, followed by Burgers, Salad, and Pasta.",
    {
      "type": "image",
      "path": "lib/assets/images/img9.png",
    },
    "Explanation:",
    "Pie charts are useful for showing how different parts contribute to a whole. The size of each slice represents the proportion of that category in relation to the total.",
  ],
  "lesson16": [
    "Objective: By the end of this lesson, students will understand what integers are, identify subsets of integers, and distinguish between positive, negative, and zero integers.",
    "Introduction to Integers",
    "Definition: Integers are the set of whole numbers that include all positive numbers, negative numbers, and zero. They are represented as {..., -3, -2, -1, 0, 1, 2, 3, ...}.",
    "Examples:",
    "Positive integers: 1, 2, 3, 4, …",
    "Negative integers: -1, -2, -3, -4, …",
    "Zero: 0 (Neither positive nor negative)",
    "Subsets of Integers",
    "Natural Numbers (Counting Numbers): These are the positive integers starting from 1. {1, 2, 3, …}",
    "Whole Numbers: These include all natural numbers and zero. {0, 1, 2, 3, …}",
    "Negative Integers: These are the negative counterparts of the natural numbers. {-1, -2, -3, …}",
    "Example:",
    "If asked to list the integers between -3 and 3, the answer would be {-3, -2, -1, 0, 1, 2, 3}.",
    "Explanation:",
    "Integers are essential for representing values below zero, like temperatures or financial losses, and they include their positive counterparts. Understanding the subsets of integers helps students differentiate between types of numbers.",
  ],
  "lesson17": [
    "Objective: By the end of this lesson, students will be able to add and subtract integers, understanding how positive and negative numbers interact.",
    "Addition of Integers",
    "Rules for Adding Integers:",
    "Same Sign: Add the absolute values of the numbers and keep the sign.",
    "Example: 5 + 3 = 8, and (-5) + (-3) = -8",
    "Different Sign: Subtract the smaller absolute value from the larger absolute value, and keep the sign of the larger number.",
    "Example: 5 + (-3) = 2, and (-5) + 3 = -2",
    "Subtraction of Integers",
    "Rules for Subtracting Integers:",
    "Subtracting a number is the same as adding its opposite.",
    "Example: 7 - 4 = 7 + (-4) = 3, and (-7) - (-4) = -7 + 4 = -3",
    "Examples:",
    "6 + (-8) = -2",
    "-9 - (-2) = -9 + 2 = -7",
    "3 + (-5) = -2",
    "Explanation:",
    "The key to adding and subtracting integers is understanding the relationship between positive and negative numbers. Visual aids like number lines can be helpful to demonstrate how numbers shift left or right depending on whether you're adding or subtracting.",
  ],
  "lesson18": [
    "Objective: By the end of this lesson, students will be able to multiply and divide integers and apply the correct sign rules.",
    "Multiplication of Integers",
    "Rules for Multiplying Integers:",
    "Same Sign: Multiply the absolute values of the numbers. The result is positive.",
    "Example: 4 × 3 = 12, and (-4) × (-3) = 12",
    "Different Sign: Multiply the absolute values, and the result is negative.",
    "Example: 4 × (-3) = -12, and (-4) × 3 = -12",
    "Division of Integers",
    "Rules for Dividing Integers:",
    "Same Sign: Divide the absolute values. The result is positive.",
    "Example: 12 ÷ 3 = 4, and (-12) ÷ (-3) = 4",
    "Different Sign: Divide the absolute values, and the result is negative.",
    "Example: 12 ÷ (-3) = -4, and (-12) ÷ 3 = -4",
    "Examples:",
    "6 × (-5) = -30",
    "(-10) ÷ 2 = -5",
    "(-9) × (-4) = 36",
    "Explanation:",
    "When multiplying or dividing integers, the primary focus is determining whether the result will be positive or negative, followed by performing the basic multiplication or division.",
  ],
  "lesson19": [
    "Objective: By the end of this lesson, students will understand and apply the correct order of operations (GEMDAS) to evaluate mathematical expressions.",
    "The GEMDAS Rule",
    "GEMDAS:",
    "Grouping (Parentheses, brackets, etc.)",
    "Exponents (Powers and roots)",
    "Multiplication and Division (from left to right)",
    "Addition and Subtraction (from left to right)",
    "Steps for Evaluating Expressions Using GEMDAS:",
    "Groupings: Simplify inside any parentheses or brackets.",
    "Exponents: Solve powers or roots.",
    "Multiplication/Division: Perform multiplication or division from left to right.",
    "Addition/Subtraction: Perform addition or subtraction from left to right.",
    "Example:",
    "Evaluate 5 + 2 × (3² - 1)",
    "Step 1: Simplify inside parentheses: 3² - 1 = 9 - 1 = 8",
    "Step 2: Multiply: 2 × 8 = 16",
    "Step 3: Add: 5 + 16 = 21",
    "Explanation:",
    "Following the GEMDAS rule ensures that mathematical expressions are evaluated in the correct sequence to avoid errors.",
  ],
  "lesson20": [
    "Objective: By the end of this lesson, students will understand the concept of absolute value and how to find the absolute value of integers.",
    "Definition of Absolute Value",
    "Absolute Value: The absolute value of a number is its distance from zero on a number line, regardless of direction. It is always positive.",
    "Symbol: |x| represents the absolute value of x.",
    "Examples: |5| = 5, and |-5| = 5",
    "Examples:",
    "|7| = 7",
    "|-9| = 9",
    "|0| = 0",
    "Explanation:",
    "Absolute value is useful in many mathematical contexts, particularly when only the magnitude (size) of a number is needed without regard to its direction (positive or negative).",
    "Special Notes:",
    "The absolute value of 0 is 0 because it is already at zero and has no distance.",
    "Absolute value always results in a positive value or zero — never negative.",
    "More Examples:",
    "|12| = 12 → 12 is 12 units away from 0.",
    "|-8| = 8 → -8 is also 8 units away from 0.",
    "|23| = 23 → 23 is 23 units away from 0.",
    "|-1| = 1 → -1 is 1 unit away from 0.",
    
  ],
  "lesson21": [
    "Objective: By the end of this lesson, students will understand how to solve simple linear equations using bar models. This visual approach will help learners better grasp the concept of balancing equations and understanding variable relationships.",
    "Introduction",
    "In algebra, equations are statements that show two expressions are equal. To solve an equation, we need to find the value of the unknown variable that makes the equation true. One way to visualize and solve simple equations is by using bar models. These models represent the quantities in an equation as lengths of bars.",
    "What is a Bar Model?",
    "A bar model is a visual representation of a mathematical problem using bars to illustrate quantities, parts, and wholes. It’s particularly helpful when working with algebraic equations because it allows students to \"see\" how different terms relate to each other.",
    "Steps to Solve Equations with a Bar Model:",
    "Understand the Problem",
    "Read the equation carefully and identify the knowns (numbers) and the unknown (variable).",
    "Draw the Bar Model",
    "Draw a rectangular bar to represent the total quantity.",
    "Divide the bar into sections to represent different parts, including the unknown quantity.",
    "Label the Parts",
    "Label each section of the bar with the known values or variables.",
    "Form the Equation",
    "Write an equation that represents the relationships shown in the bar model.",
    "Solve the Equation",
    "Use algebraic techniques (like addition, subtraction, multiplication, or division) to solve for the unknown.",
    "Example 1: Solving a Simple Equation",
    "Problem: Solve the equation x+5=12",
    "Step 1: Understand the Problem",
    "We need to find the value of x, knowing that when 5 is added to xxx, the total equals 12.",
    "Step 2: Draw the Bar Model",
    "Draw a bar representing the total of 12.",
    "Divide the bar into two parts: one part for x (the unknown) and one part for 5 (the known number).",
    {
      "type": "image",
      "path": "lib/assets/images/img10.png",
    },
    "Step 3: Label the Parts",
    "One part is labeled as x, and the other is labeled as 5. The total length of the bar is 12.",
    "Step 4: Form the Equation",
    "The model shows that x+5=12",
    "Step 5: Solve the Equation",
    "To solve for x, subtract 5 from both sides:",
    {
      "type": "image",
      "path": "lib/assets/images/img11.png",
    },
    {
      "type": "image",
      "path": "lib/assets/images/img12.png",
    },
    "x=12−5",
    "x=7",
    "So, the value of x is 7.",
    "Using bar models to solve simple equations can be a powerful tool for visual learners. It helps break down the equation into manageable parts, making it easier to understand and solve. Practice with different types of equations to master this method!",
  ],
  "lesson22": [
    "Objective:",
    "By the end of this lesson, students will understand how to evaluate algebraic expressions by substituting variables with given values and applying the correct order of operations.",
    "Introduction to Algebraic Expressions",
    "An algebraic expression is a mathematical phrase that includes numbers, variables (letters representing unknown values), and operations (addition, subtraction, multiplication, division).",
    "Examples:",
    "3x+5",
    "4y2−7",
    "2a+3b−4",
    "Explanation:",
    "A variable is a letter used to represent an unknown or changing number (e.g., x,y,ax, y, ax,y,a).",
    "A constant is a fixed value (e.g., 7 or -10).",
    "A numerical coefficient is the number multiplied by a variable (e.g., 3 in 3x).",
    "A term can be a number, a variable, or a combination of both.",
    "Scenario: Joey helps his mother sell corncobs at ₱25 each. The number of corncobs sold each day is different.",
    "Examples:",
    "If they sell 20 corncobs: 20 × ₱25 = ₱500",
    "If they sell 27 corncobs: 27 × ₱25 = ₱675",
    "If they sell x corncobs: ₱25 × x = ₱25x",
    "Explanation:",
    "x is the variable (number of corncobs sold)",
    "25x is an algebraic expression representing daily income",
    "Definition: An exponent shows how many times a number (called the base) is multiplied by itself.",
    "Examples:",
    "5^2 = 5 x 5 =25",
    "5^3 = 5 x 5 x 5 = 125",
    "y^m= y x y x y x y……x y(multiply y by itself m times)",
    "Explanation:",
    "In x^4 where x is the base, and 4 is the exponent",
    "This means multiplying x by itself 4 times",
    "Evaluate the following expressions using the given values:",
    "1. 2x + y when x=3 and y=4: 2(3)+4 = 6+4 =10",
    "2. 4(2^2) - 6= 4(4)-6 = 16-6 = 10",

  ],
  "lesson23": [
    "Objective:",
    "Students will learn how to translate real-world situations and word problems into algebraic equations.",
    "What is an Algebraic Equation?",
    "An algebraic equation is a mathematical statement that shows the equality between two expressions, often containing one or more variables (unknowns). It usually looks like this:",
    "Expression 1=Expression 2",
    "For example:",
    "2x+5=15",
    "Here, x is the variable, and the equation says that when you add 5 to 2 times some number (x), the result is 15.",
    "Steps to Write Algebraic Equations",
    "Step 1: Understand the Problem",
    "Read the problem carefully. Look for key phrases that indicate mathematical operations (addition, subtraction, multiplication, division).",
    "Step 2: Define the Variable",
    "Identify what the unknown is, and assign it a variable, like xxx or yyy.",
    "Step 3: Translate the Words into an Equation",
    "Convert the words and actions into mathematical symbols.",
    "Step 4: Form the Equation",
    "Put together the equation using the variable, constants, and mathematical operations.",
    "Common Words and Their Mathematical Translations",
    "Addition: sum, plus, increased by, more than",
    "Example: \"5 more than a number\" → x+5",
    "Subtraction: minus, less, decreased by, difference",
    "Example: \"7 less than a number\" → x−7",
    "Multiplication: times, product, multiplied by",
    "Example: \"3 times a number\" → 3x",
    "Division: divided by, quotient, per",
    "Example: \"A number divided by 4\" → x/4",
    "Example Problems",
    "Example 1:",
    "Problem: The sum of a number and 8 is equal to 12.",
    "Understand the Problem:",
    "We need to find a number that, when added to 8, gives 12.",
    "Define the Variable:",
    "Let the unknown number be x.",
    "Translate into an Equation:",
    "x+8=12",
    "Solve the Equation:",
    "Subtract 8 from both sides:",
    "x=12−8",
    "x=4",
    "Example 2:",
    "Problem: A number multiplied by 6 equals 42.",
    "Understand the Problem:",
    "We need to find a number that, when multiplied by 6, gives 42.",
    "Define the Variable:",
    "Let the unknown number be x.",
    "Translate into an Equation:",
    "6x=42",
    "Solve the Equation:",
    "Divide both sides by 6:",
    "x=42/6",
    "x=7",
    "Writing algebraic equations from word problems is a critical skill in solving real-world problems. By practicing these steps, students will improve their ability to translate situations into mathematical language and solve for unknowns.",
  ],
  "lesson24": [
    "Objective:",
    "By the end of this lesson, students will be able to:",
    "Identify and apply the different properties of equality to solve algebraic equations.",
    "What is Equality?",
    "In mathematics, equality means that two expressions are equivalent in value. An equation, which includes the equals sign (=), asserts that the value on the left side is the same as the value on the right side.",
    "For example:",
    "3+4=7",
    "Here, the expression \"3 + 4\" is equal to \"7\".",
    "Key Properties of Equality Used in Solving Equations",
    "These four properties allow us to solve equations while keeping both sides balanced:",
    "1. APE – Addition Property of Equality",
    "Definition: If two expressions are equal, adding the same number to both sides keeps them equal.",
    "Rule: If a=b then a+c=b+c ",
    "Example1: If x=4, then x+2= 4+2 ⇒ x+2 =6",
    "Example2: If y−3=5, add 3 to both sides: y−3+3=5+3⇒y=8",
    "2. SPE – Subtraction Property of Equality",
    "Definition: If two expressions are equal, subtracting the same number from both sides keeps them equal.",
    " Rule: Rule: If a=b then a−c=b−c",
    "Example1: If y=10, then y−3=10−3⇒y−3=7",
    "Example2: If x+7=12, subtract 7 from both sides: x+7−7=12−7⇒x=5",
    "3. MPE – Multiplication Property of Equality",
    "Definition: If two expressions are equal, multiplying both sides by the same number keeps them equal.",
    "Rule: If a=b, then a*c=b*c",
    "Example1: If x=5, then x*2=5*2⇒x*2=10",
    "Example2: If x/4=3, multiply both sides by 4: x/4 *4=3*4⇒x=12",
    "4. DPE – Division Property of Equality",
    "Definition: If two expressions are equal, dividing both sides by the same non-zero number keeps them equal.",
    "Rule: If a=b, then a/c=b/c(as long as c≠0).",
    "Example1: If x=12, then x/3=12/3⇒x/3=4",
    "Example2: If 5/x=20, divide both sides by 5:  5x/5=20/5⇒x=4",
    "Summary",
    "The properties of equality—APE, SPE, MPE, and DPE—are tools we use to keep equations balanced while solving for unknowns. By using these steps carefully, we can isolate variables and find accurate solutions.",
    
  ],
  "lesson25": [
    "Objective:",
    "By the end of this lesson, students will be able to:",
    "Understand how to write algebraic equations from word problems or real-life situations.",
    "Apply methods to solve linear equations with one variable.",
    "Introduction to Equations",
    "What is an Equation?",
    "An equation is a mathematical statement that shows the equality of two expressions.",
    "It uses the equal sign = to show that two sides are equivalent.",
    "Example:",
    "3x+5=20",
    "In this equation, 3x + 5 is on the left side and 20 is on the right side, and they are equal.",
    "II. Writing Equations from Word Problems",
    "Step 1: Identify the Variables",
    "Variables represent unknown quantities in the equation. For example, “x” could represent the number of items, a distance, or an amount.",
    "Step 2: Translate Words to Math",
    "Identify keywords in the problem and match them to their mathematical operations.",
    "Addition: \"sum,\" \"plus,\" \"increased by\"",
    "Subtraction: \"difference,\" \"minus,\" \"decreased by\"",
    "Multiplication: \"times,\" \"product,\" \"of\"",
    "Division: \"quotient,\" \"divided by,\" \"per\"",
    "Step 3: Write the Equation",
    "Combine the variables and constants based on the relationships described in the word problem.",
    "Example 1:",
    "Problem: Sarah bought 3 apples and the total cost was \$12. Each apple costs the same amount. What is the cost of one apple?",
    "Writing the Equation: Let x be the cost of one apple. 3x=12",
    "Solve: x=12/3=4",
    "Solving Linear Equations",
    "A linear equation is an equation where the variable is raised only to the first power. The general form is:",
    "ax+b=c",
    "where a, b, and c are constants, and x is the variable.",
    "Steps to Solve a Linear Equation",
    "Isolate the Variable: Use inverse operations to move constants to one side of the equation.",
    "Simplify: Combine like terms.",
    "Solve for the Variable: After isolating the variable, find its value.",
    "Example 2: Solving a Simple Equation",
    "Solve 2x+4=10",
    "Step 1: Subtract 4 from both sides:",
    "2x=10−4",
    "2x=6",
    "Step 2: Divide by 2:",
    "x=6/2",
    "x=3",
  ],
  "lesson26": [
    "Objective:",
    "By the end of this lesson, students will understand the concept of outcomes in probability and how to calculate them in various scenarios.",
    "What are Outcomes?",
    "In math, particularly in probability, an outcome is a possible result of an experiment or event. For example, when flipping a coin, the possible outcomes are heads or tails.",
    "Example:",
    "Experiment: Flipping a coin",
    "Outcomes: Heads (H), Tails (T)",
    "Sample Space",
    "The set of all possible outcomes of an experiment is called the sample space. It contains every outcome that can occur.",
    "Example 1: Flipping a coin",
    "Sample Space (S): {H, T}",
    "Example 2: Rolling a six-sided die",
    "Sample Space (S): {1, 2, 3, 4, 5, 6}",
    "Types of Outcomes",
    "Equally likely outcomes: All outcomes have the same chance of occurring.",
    "Unequally likely outcomes: Some outcomes are more likely to occur than others.",
    "Example of Equally Likely Outcomes:",
    "Rolling a fair six-sided die. Each number (1 through 6) has an equal chance of appearing, so each outcome has a probability of 1/6.",
    "Example of Unequally Likely Outcomes:",
    "Picking a red or blue marble from a bag with 3 red marbles and 1 blue marble. Red is more likely than blue.",
    "Calculating Outcomes",
    "When dealing with more complex situations, like multiple events, calculating outcomes becomes more detailed. Let’s explore a few methods.",
    "A. The Counting Principle",
    "If one event has \"m\" possible outcomes and another independent event has \"n\" possible outcomes, then there are m × n possible outcomes for both events combined.",
    "Example:",
    "Event 1: Flip a coin (2 outcomes: H, T)",
    "Event 2: Roll a die (6 outcomes: 1, 2, 3, 4, 5, 6)",
    "The total number of outcomes = 2 × 6 = 12 outcomes.",
    "B. Tree Diagrams",
    "A tree diagram is a visual way to represent all possible outcomes of one or more events. It clarifies multi-step experiments.",
    "Example: Flipping two coins",
    "First Coin: H or T",
    "Second Coin: H or T",
    "The tree diagram would show four possible outcomes: HH, HT, TH, TT.",
    "Examples & Practice Problems",
    "Example 1: Rolling a die",
    "What is the probability of rolling an even number?",
    "Favorable outcomes: {2, 4, 6}",
    "Total outcomes: 6",
    "P(even number)=3/6=1/2​",
    "Example 2: Drawing a card from a standard deck",
    "What is the probability of drawing a heart from a deck of 52 cards?",
    "Favorable outcomes: 13 hearts",
    "Total outcomes: 52",
    "P(heart)=13/52=1/4​",
  ],
  "lesson27": [
    "Objective:",
    "By the end of this lesson, students will be able to:",
    "Understand how to read and interpret tables and graphs.",
    "Recognize the different types of graphs (bar charts, line graphs, pie charts, etc.).",
    "Use tables to organize data and graphs to visualize that data effectively.",
    "What is Frequency?",
    "Frequency refers to the number of times a particular value or event occurs within a dataset.",
    "Example: If we survey a class of 30 students about their favorite color and 10 say \"blue,\" the frequency of blue is 10.",
    "Frequency Table",
    "A frequency table helps organize data by showing how often each value or category appears.",
    "Example: We ask 20 students their favorite fruits, and the results are:",
    "Apple: 6 students",
    "Banana: 5 students",
    "Orange: 4 students",
    "Mango: 3 students",
    "Grapes: 2 students",
    "We create a frequency table to represent this data:",
    {
      "type": "image",
      "path": "lib/assets/images/img13.png",
    },
    "Visualizing Frequency Data Using Graphs",
    "Graphs help present frequency data in a more visually appealing way. Let's explore different types of graphs:",
    "A. Bar Graph",
    "A bar graph uses bars to represent the frequency of categories. Each bar's height corresponds to the frequency.",
    {
      "type": "image",
      "path": "lib/assets/images/img14.png",
    },
    "B. Pie Chart",
    "A pie chart represents data as slices of a circle, with each slice proportional to the frequency of the category.",
    "Example (Pie Chart for Fruit Data):",
    "Total = 20 students.",
    "Apple = 6/20 (30% of the circle), Banana = 5/20 (25%), Orange = 4/20 (20%), Grapes =5/20 (25%)",
    {
      "type": "image",
      "path": "lib/assets/images/img15.png",
    },
    "Steps to create a bar graph:",
    "Draw the x-axis (categories) and y-axis (frequency).",
    "Label each axis.",
    "Draw bars for each category based on their frequency.",
    {
      "type": "image",
      "path": "lib/assets/images/img16.png",
    },
    "C. Line Graph",
    "A line graph is used to display data points that are connected by lines, showing changes or trends over time. It is useful when tracking data that changes over a continuous interval.",
    "Steps to create a line graph:",
    "Draw the x-axis (time or continuous data) and y-axis (frequency or numerical value).",
    "Label each axis.",
    "Plot the data points for each category (for example, if you are tracking the number of students' favorite fruit over several days or weeks).",
    "Connect the data points with lines to show the trend.",
    "Example (Simple Line Graph for Fruit Data):",
    "Imagine we surveyed 5 students about their favorite fruit on different days. Here’s the data:",
    {
      "type": "image",
      "path": "lib/assets/images/img17.png",
    },
    "To create a Line Graph:",
    "x-axis: Days (1, 2, 3, 4, 5)",
    "y-axis: Number of Students (0 to 5)",
    "Now, plot the data points for Apple and Banana separately:",
    "Day 1: Apple = 1, Banana = 0",
    "Day 2: Apple = 2, Banana = 1",
    "Day 3: Apple = 3, Banana = 1",
    "Day 4: Apple = 4, Banana = 2",
    "Day 5: Apple = 5, Banana = 3",
    "Next, connect the points with lines for each fruit. This shows how the number of students who liked Apple and Banana increased over the 5 days.",
    {
      "type": "image",
      "path": "lib/assets/images/img18.png",
    },
  ],
  "lesson28": [
    "Objective: By the end of this lesson, students will be able to:",
    "Understand the purpose and use of scientific notation.",
    "Convert numbers from standard form to scientific notation and vice versa.",
    "Perform basic operations (addition, subtraction, multiplication, and division) using scientific notation.",
    "Introduction to Scientific Notation",
    "Scientific notation is a way to express very large or very small numbers in a concise, manageable form. It is commonly used in fields like physics, astronomy, and engineering where dealing with extremely large or small values is routine.",
    "Why Use Scientific Notation?",
    "It simplifies the reading and writing of large numbers.",
    "It allows for easier calculation when dealing with powers of ten.",
    "Structure of Scientific Notation",
    "A number in scientific notation is written in the form:",
    "a×10n",
    "Where:",
    "a is a number (called the coefficient) that is greater than or equal to 1 but less than 10.",
    "10n is the power of ten that indicates how many times to multiply or divide by 10.",
    "Example:",
    "3.45×106 is the scientific notation of 3,450,000.",
    "5.6×10−3 is the scientific notation of 0.0056.",
    "Converting to Scientific Notation",
    "Large Numbers:",
    "To convert a large number to scientific notation:",
    "Move the decimal point to the left until the number becomes a value between 1 and 10.",
    "Count how many places you moved the decimal point. This number becomes the exponent of 10.",
    "Example: Convert 75,000,000 to scientific notation:",
    "Move the decimal point 7 places to the left: 7.5×107",
    "Small Numbers:",
    "For small numbers (less than 1), the process is similar:",
    "Move the decimal point to the right until the number becomes a value between 1 and 10.",
    "Count how many places you moved the decimal point. This number will be negative and becomes the exponent of 10.",
    "Example: Convert 0.00042 to scientific notation:",
    "Move the decimal point 4 places to the right: 4.2×10−4",
    "Converting from Scientific Notation to Standard Form",
    "Large Exponents:",
    "To convert from scientific notation to standard form, move the decimal point to the right according to the exponent of 10.",
    "Example: Convert 6.1×105 to standard form:",
    "Move the decimal point 5 places to the right: 610,000",
    "Negative Exponents:",
    "For negative exponents, move the decimal point to the left.",
    "Example: Convert 3.2×10−3 to standard form:",
    "Move the decimal point 3 places to the left: 0.0032",
    "Operations in Scientific Notation",
    "Multiplication:",
    "When multiplying numbers in scientific notation:",
    "Multiply the coefficients.",
    "Add the exponents.",
    "Example:",
    "(2×103)×(3×104) = (2×3)×103+4 = 6×107",
    "Division:",
    "When dividing numbers in scientific notation:",
    "Divide the coefficients.",
    "Subtract the exponents.",
    "Example:",
    "8×106/2×102 = 8/2×106−2 = 4×104",
    "Addition and Subtraction:",
    "To add or subtract numbers in scientific notation, the exponents must be the same.",
    "If the exponents are different, convert one number so both have the same exponent.",
    "Add or subtract the coefficients.",
    "Example:",
    "(5.2×103) + (3.1×102)",
    "Convert 3.1×102 to 0.31×103",
    "(5.2×103) +(0.31×103) = (5.2+0.31) × 103=5.51×103",
  ],
};
